# Generated by Django 5.0.6 on 2024-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок записи')),
                ('description', models.TextField(verbose_name='Текст записи')),
                ('author', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('data', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Записи',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
